global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  # no rules
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
      - targets: ['prometheus_node_exporter:9100']
